apiVersion: v2
name: todo
description: Todo Application Helm Chart - Phase V Cloud Deployment with Event-Driven Architecture
type: application
version: 2.0.0
appVersion: "2.0.0"

keywords:
  - todo
  - fastapi
  - nextjs
  - kubernetes
  - hackathon

home: https://github.com/mashdotdev/hackathon-2-todo

maintainers:
  - name: Todo Team
    email: team@example.com

sources:
  - https://github.com/mashdotdev/hackathon-2-todo

dependencies: []
