apiVersion: v2
name: todo
description: Todo Application Helm Chart - Phase IV Local Kubernetes Deployment
type: application
version: 0.4.0
appVersion: "0.4.0"

keywords:
  - todo
  - fastapi
  - nextjs
  - kubernetes
  - hackathon

home: https://github.com/mashdotdev/hackathon-2-todo

maintainers:
  - name: Todo Team
    email: team@example.com

sources:
  - https://github.com/mashdotdev/hackathon-2-todo

dependencies: []
