{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo.fullname" . }}-frontend-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "todo.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  NEXT_PUBLIC_API_URL: {{ .Values.frontend.config.apiUrl | quote }}
{{- end }}
