{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo.fullname" . }}-backend-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "todo.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  LOG_LEVEL: {{ .Values.backend.config.logLevel | quote }}
  CORS_ORIGINS: {{ .Values.backend.config.corsOrigins | quote }}
{{- end }}
