{{- if .Values.dapr.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo.fullname" . }}-kafka-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "todo.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.dapr.kafka.bootstrapServers }}"
  KAFKA_TOPICS_TASK_EVENTS: "task-events"
  KAFKA_TOPICS_REMINDERS: "reminders"
  KAFKA_TOPICS_TASK_UPDATES: "task-updates"
{{- end }}
