{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo.fullname" . }}-frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "todo.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  {{- if .Values.frontend.strategy }}
  strategy:
    type: {{ .Values.frontend.strategy.type }}
    {{- if eq .Values.frontend.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.frontend.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.frontend.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "todo.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "todo.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "todo.fullname" . }}-frontend-config
          {{- if .Values.frontend.probes.liveness }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.liveness.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end }}
