{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "todo.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.databaseUrl }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.secretKey }}
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.geminiApiKey }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
