{{- if and .Values.dapr.enabled .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "todo.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.dapr.kafka.username | b64enc | quote }}
  password: {{ .Values.dapr.kafka.password | b64enc | quote }}
{{- end }}
